name: CICD

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'

      - name: Run build
        run: GOOS=windows GOARCH=amd64 go build .

      - name: Pack
        run: |
          mkdir goguming-win
          cp game.exe goguming-win/
          cp -r img/ goguming-win/img/
          cp -r levels/ goguming-win/levels/
          zip -r goguming-win.zip goguming-win
          ls

      - name: Deploy
        run: echo Will save to artifacts here
