name: CICD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'

      - name: Build binaries
        run: GOOS=windows GOARCH=amd64 go build .

      - name: Build frontend
        run: |
          cd front
          yarn
          yarn build

      - name: Pack
        run: |
          mkdir goguming-win
          cp game.exe goguming-win/
          mkdir goguming-win/img/
          cp -r img/*.png goguming-win/img/
          cp -r levels/ goguming-win/levels/
          cp -r static/ goguming-win/static/
          zip -r goguming-win.zip goguming-win

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: goguming-win.zip
